### PR TITLE
Some rodex fixes

### LINKED ISSUE #1977: nullpo rodex
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

The Rodex system is occurring nullpo error when deleting, but need to do some steps to get the error.

sem titulo

**Client:** 2018-01-24bRagexeRE

The NPC used for testing is just below

```c
prontera,150,150,4	script	Rodex Mail	1_M_01,{
	rodex_sendmail(
		getcharid(CHAR_ID_CHAR), "Rodex Test", "Rodex Test1", "Hello World, How are You?",
		1000,
		Red_Potion, 5
	);
	end;
}
```

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)
### Steps To Reproduce The Issue

**1.** Talk to the NPC and get the reward, open rodex and pick up the items and zeny, but do not remove the email yet

**2.** Talk to the NPC again, take the items and Zeny, do not remove message yet

**3.** Close the Rodex and open again, select the two messages and try to remove only one will be removed, and the other will cause nullpo error. Relog and try to remove the message, and now it is possible to remove.

**Note:** Sometimes it is removed correctly, try until you get nullpo error 

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: 59f02f1d406a1238f90d072949ac07279a90e9ea

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

### PR DESCRIPTION
**Pull request by guilherme-gm**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)
* Fix a wrong behavior with returned messages
* Fixes nullpo when user tried to do actions in an unloaded mail
* Fixes a missing update that made mail undeletable in some cases

**Affected Branches:** 

[//]: # (Master? Slave?)
master

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)
* Fixes #1977 

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)
~

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1987)

File: sql-files/main.sql [hunk 1]
```diff
@@ -965,6 +966,7 @@ CREATE TABLE IF NOT EXISTS `rodex_mail` (
 	`zeny` BIGINT(20) NOT NULL,
 	`type` TINYINT(8) UNSIGNED NOT NULL,
 	`is_read` TINYINT(8) NOT NULL,
+  `sender_read` TINYINT(2) NOT NULL,
```
Comment (4144) [inline sql-files/main.sql]: look like formatting bit wrong. probably here should be tab before `sender_read` TINYINT(2) NOT NULL,

File: src/char/int_rodex.c [hunk 2]
```diff
@@ -95,9 +95,12 @@ static int inter_rodex_fromsql(int char_id, int account_id, int8 opentype, int64
 	case RODEX_OPENTYPE_UNSET:
 		if (SQL_ERROR == SQL->StmtPrepare(stmt,
 			"SELECT `mail_id`, `sender_name`, `sender_id`, `receiver_name`, `receiver_id`, `receiver_accountid`,"
-			"`title`, `body`, `zeny`, `type`, `is_read`, `send_date`, `expire_date`, `weight`"
-			"FROM `%s` WHERE `expire_date` > '%d' AND (`receiver_id` = '%d' or `receiver_accountid` = '%d') AND `mail_id` > '%"PRId64"'"
-			"ORDER BY `mail_id` ASC", rodex_db, (int)time(NULL), char_id, account_id, mail_id)
+			"`title`, `body`, `zeny`, `type`, `is_read`, `sender_read`, `send_date`, `expire_date`, `weight`"
+			"FROM `%s` WHERE "
+			"((`expire_date` > '%d' AND(`receiver_id` = '%d' OR `receiver_accountid` = '%d'))"
+			"OR(`is_read` = 0 AND `sender_id` = '%d' AND `expire_date` <= '%d' AND `send_date` + '%d' > '%d'))"
```
Comment (4144) [inline src/char/int_rodex.c]: after OR and after AND need space

**Comment by tlacson7** [comment]
mail can't be deleted:
1. receive any mail
2. get all item and zeny
3. close the mail
4. open same mail again.  You will see "Receive"  Click "Receive" even no items left to claim.
5. delete mail. < failed.

**Comment by guilherme-gm** [comment]
@tlacson7 what client date are you using?

**Comment by tlacson7** [comment]
#define PACKETVER 20151029

**Comment by guilherme-gm** [comment]
I'm not able to reproduce it
rodexif

File: src/map/rodex.c [hunk 3]
```diff
@@ -395,7 +395,8 @@ void rodex_read_mail(struct map_session_data *sd, int64 mail_id)
 	nullpo_retv(sd);
 
 	msg = rodex->get_mail(sd, mail_id);
-	nullpo_retv(msg);
+	if (msg == NULL)
```
Comment (4144) [inline src/map/rodex.c]: probably better add exclude condition for not show nullpo error for example if mail_id is zero or other what can get from non official clients?
because nullpo can catch unknown errors.
