### PR TITLE
Fixes #2173

### LINKED ISSUE #2173: Char server crash when delete character who is guild leader with char id below default
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

Note: I am using Dastgir's storage expansion plugin (only char edit I can think of).

### Background
Okay I don't know quite how to explain this one but I'll give it a go.
- First, my database has some old data on it, char ids below 150000.
- `use_aegis_delete` set to **false** so I should be able to delete even though I'm in a guild, but actually client will forbid me from deleting.
- Client version `2016-01-13bRagexe`.

### How I executed char server crash
- Character A char id is below 150000 (the lowest, but this is an old db with lower char ids).
- Character A is set to delete while in guild (is guild leader). This was possible due to using a different client I previously used, I guess.
- Character A gets deleted.
- Char server crashes.

This does not happen to every character who is GL, but it can happen just wanted to let you guys know.

### PR DESCRIPTION
**Pull request by dastgirp**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)
Fixes crash when character is removed from `char` table but not from guild_member.

**Affected Branches:** 

[//]: # (Master? Slave?)

**Issues addressed:**

#2173 

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

On Long term, we need foreign keys to ensure this does not happen

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2209)

File: src/char/int_guild.c [hunk 1]
```diff
@@ -443,7 +443,9 @@ static struct guild *inter_guild_fromsql(int guild_id)
 		if( m->position >= MAX_GUILDPOSITION ) // Fix reduction of MAX_GUILDPOSITION [PoW]
 			m->position = MAX_GUILDPOSITION - 1;
 		SQL->GetData(inter->sql_handle, 11, &data, &len); memcpy(m->name, data, min(len, NAME_LENGTH));
-		SQL->GetData(inter->sql_handle, 12, &data, NULL); m->last_login = atoi(data);
+		SQL->GetData(inter->sql_handle, 12, &data, NULL);
+		if (data != NULL)
+			m->last_login = atoi(data);
```
Comment (4144) [inline src/char/int_guild.c]: this kind of check i think need in many places in code where used strings from db without checks

Comment (dastgirp) [reply src/char/int_guild.c]: so maybe adding foreign keys is the best solution, instead of these checks
