### PR TITLE
fix setting char/account variables of another player 

### LINKED ISSUE #2212: set(getvariableofpc(<var>, <account id>), <val>) crashes map server
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [ ] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

I am using Gepard Shield.

### Description

A script I made crashes the server. It involved `set(getvariableofpc())`.

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. I used these commands to create a mute log for a player. Already checked player is logged in earlier in script.
```
set(getvariableofpc(#Mute_Log[0], .@tsd), .@Amount + 1);
set(getvariableofpc(#Mute_Log[1], .@tsd), .@Original + .@Time);
```
2. Once script is done executing, log out. The server will crash with the following log/reference (using gdb).
https://pastebin.com/dcRmP7Jd

I can send my full script to somebody if they want to test.

**Branch(es):**
- [x] master
- [x] stable

### Operating System

CentOS7.4

### PR DESCRIPTION
**Pull request by Helianthella**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
`building_getvariableofpc` __never__ actually worked when using it to set char-scope or account-scope variables

This PR fixes the following bugs:
- `set_reg_pc_ref_num` was incorrectly setting the type to `1`, which made `script_reg_destroy` behave unexpectedly
- `set_reg_pc_ref_num` was not setting the `vars_dirty` flag _at all_, which made map server not send the updated vars to char server
  - ⚠ **possible exploit**: if a script sets an account variable on another char, the player can just logout and the variable will not be updated
- `building_getvariableofpc` was not using the right option for `i64db_alloc`
- `set_reg_pc_ref_num` was unable to set "special" variables, such as `#KAFRAPOINTS`

<br><br>

closes #2212 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2238)

File: src/map/script.c [hunk 1]
```diff
@@ -3398,13 +3411,26 @@ static void set_reg_pc_ref_num(struct script_state *st, struct reg_db *n, int64
...
 
 		if(n->vars->put(n->vars, DB->i642key(num), DB->ptr2data(p), &prev)) {
 			p = DB->data2ptr(&prev);
 			ers_free(pc->num_reg_ers, p);
 		}
 	}
+
+	if (!pc->reg_load && p != NULL) {
+		struct DBIterator *iter = db_iterator(map->pc_db);
+		struct map_session_data *sd = NULL;
```
Comment (4144) [inline src/map/script.c]: sd better define inside for ``for (struct map_session_data *sd = ...``

File: src/map/script.c [hunk 2]
```diff
@@ -20698,7 +20724,7 @@ static BUILDIN(getvariableofpc)
 	}
 
 	if (!sd->regs.vars)
-		sd->regs.vars = i64db_alloc(DB_OPT_RELEASE_DATA);
+		sd->regs.vars = i64db_alloc(DB_OPT_BASE);
```
Comment (4144) [inline src/map/script.c]: is this is memory leak?

File: src/map/script.c [hunk 3]
```diff
@@ -3361,6 +3361,19 @@ static void set_reg_pc_ref_str(struct script_state *st, struct reg_db *n, int64
 			ers_free(pc->str_reg_ers, p);
 		}
 	}
+
+	if (!pc->reg_load && p != NULL) {
+		struct DBIterator *iter = db_iterator(map->pc_db);
+		struct map_session_data *sd = NULL;
```
Comment (4144) [inline src/map/script.c]: sd better define inside for for (struct map_session_data *sd = ...

File: src/map/script.c [hunk 4]
```diff
@@ -3316,121 +3316,30 @@ static void set_reg_npcscope_str(struct script_state *st, struct reg_db *n, int6
...
-			}
-			ers_free(pc->str_reg_ers, p);
-		}
-	}
-
-	if (!pc->reg_load && p != NULL) {
-		struct DBIterator *iter = db_iterator(map->pc_db);
-		struct map_session_data *sd = NULL;
+	struct DBIterator *iter = db_iterator(map->pc_db);
+	struct map_session_data *sd = NULL;
```
Comment (4144) [inline src/map/script.c]: and here sd better move into for

File: src/map/script.c [hunk 5]
```diff
@@ -3316,121 +3316,30 @@ static void set_reg_npcscope_str(struct script_state *st, struct reg_db *n, int6
...
-			p = DB->data2ptr(&prev);
-			ers_free(pc->num_reg_ers, p);
-		}
-	}
-
-	if (!pc->reg_load && p != NULL) {
-		struct DBIterator *iter = db_iterator(map->pc_db);
-		struct map_session_data *sd = NULL;
+	struct DBIterator *iter = db_iterator(map->pc_db);
+	struct map_session_data *sd = NULL;
```
Comment (4144) [inline src/map/script.c]: and here

File: src/map/script.c (hunk 2 above)
Comment (Helianthella) [reply src/map/script.c]: nope, and this is exactly what is used in pc.c too
