### PR TITLE
Fixes close merchant vending

### LINKED ISSUE #2554: Failed in closing vending.
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
When trying to close a vending, the character freezes and can no longer move. It looks like the store is not closing properly, because when you use @refresh the store reappears even though it has been closed.

PACKETVER used: 20180404 or 20181212

### Steps To Reproduce The Issue
1. Create a store using the MC_VENDING skill (ID: 41).
2. Then close the vending.
3. At this stage your character will no longer be able to walk, he will be "frozen".
4. Use the @refresh command and notice that the Vending is still open.

**Branch(es):**
- [x] master
- [x] other

### Hercules rev. hash/commit:
Git revision src: https://github.com/HerculesWS/Hercules/commit/d026e28fd78f60dfa21da381f17f2a8cc9ae3d11

### PR DESCRIPTION
**Pull request by guilherme-gm**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This PR removes some checks that were preventing players to close their vending (from merchant skill). The issue was basically because we had a check that prevented a player in any trading state (including vending) to close it.

I also removed the check for a dead player, because the client itself allows that, and the same problem would happen.

**Issues addressed:** 
Fixes #2554 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2555)

File: src/map/clif.c [hunk 1]
```diff
@@ -14298,7 +14298,7 @@ static void clif_parse_CloseVending(int fd, struct map_session_data *sd) __attri
 /// 012e
 static void clif_parse_CloseVending(int fd, struct map_session_data *sd)
 {
-	if (pc_istrading(sd) || pc_isdead(sd))
+	if (sd->npc_id || sd->state.buyingstore || sd->state.trading)
```
Comment (4144) [inline src/map/clif.c]: probably better leave pc_isdead? Or you think dead players should close vending too?

Comment (guilherme-gm) [reply src/map/clif.c]: The original client allows you to close it while dead (tested on 2018-10), so if we keep the pc_isdead check, we will prevent them from closing while dead (although the client would still close it, as it doesn't wait for an ACK), a player could close it while dead and when they respawn the shop would be open again (client-side wise), which is a wrong behaviour.

I haven't tried, but I think adding a check that prevents them from closing while dead would also cause issues with a priest using ressurrect, example (not tested, just an idea):
- merchant dies
- merchant clicks on close (client shows it as closed / server doesn't close it)
- priest ressurrects player
- merchant still has the vending state, thus couldn't walk, but they doesn't have an open shop in their UI -> player gets stuck = bug
