### PR TITLE
Minor fixes to Asura Strike

### LINKED ISSUE #1239: Asura Strike
1. The direction changes upon using Asura Strike on a target, instead of facing your point of direction it will face on the target.
   Hercules Video:
   https://youtu.be/fE3ZpHP9hdo

2. When using Asura Strike in town (or not pvp map)  it will show "Skill has failed" twice.
   Hercules Video:
   https://youtu.be/AzeF21Jgm_g

3. On non-pvp maps (no damage): In official caster should be falling 3 cells apart from his current position but here in hercules only 2 cells on non-pvp maps.
Hercules Video:
https://youtu.be/vxUvu6pj1zk

### PR DESCRIPTION
**Pull request by guilherme-gm**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

These are small fixes to how Asura Strike skill behaves. This fixes:
* After using Asura Strike the caster doesn't end up looking to its target anymore
* When Asura Strike fails, it doesn't shows "Skill failed" twice in chat
* When Asura Strike fails, the caster will now walk 3 cells from where he originally was (instead of 2)

**Affected Branches:** 
master

**Issues addressed:**
Fixes #1239

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

Special thanks to @kyeme

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2248)

File: src/map/skill.c [hunk 1]
```diff
@@ -5831,7 +5833,8 @@ static int skill_castend_id(int tid, int64 tick, int id, intptr_t data)
 			ud->skill_lv = ud->skilltarget = 0;
 		}
 
-		if (src->id != target->id)
+		// Asura Strike caster doesn't look to its target in the end
+		if (src->id != target->id && is_asura == false)
```
Comment (dastgirp) [inline src/map/skill.c]:
```suggestion
		if (src->id != target->id && !is_asura)
```

**Comment by guilherme-gm** [comment]
@dastgirp can you check the updated version? thanks!

File: src/map/skill.c [hunk 2]
```diff
@@ -5856,19 +5859,23 @@ static int skill_castend_id(int tid, int64 tick, int id, intptr_t data)
...
+			else if (dir > 4) x = dist;
 			else x = 0;
-			if( dir > 2 && dir < 6 ) y = -2;
-			else if( dir == 7 || dir < 2 ) y = 2;
+			if (dir > 2 && dir < 6) y = -dist;
+			else if (dir == 7 || dir < 2) y = dist;
 			else y = 0;
-			if (unit->movepos(src, src->x+x, src->y+y, 1, 1)) {
+
+			if (unit->movepos(src, src->x + x, src->y + y, 1, 1)) {
```
Comment (Kenpachi2k13) [inline src/map/skill.c]: `unit->movepos(src, src->x + x, src->y + y, 1, 1) == 1`
or
`unit->movepos(src, src->x + x, src->y + y, 1, 1) != 0`

**Comment by guilherme-gm** [comment]
@Kenpachi2k13 fixed and rebased. Thanks!

File: src/map/skill.c (hunk 2 above)
Comment (skyleo) [reply src/map/skill.c]: Alright. Please NEVER use `== 1` when correcting a condition that mistreats an int as a boolean, ~~UNLESS you're 100% sure that it will never be value besides 1, and even then~~ it's a bad idea, because custom code might expect this condition here to still work the same way it was before.

This should be `!= 0`.

Comment (skyleo) [reply src/map/skill.c]: Opened an issue about this matter https://github.com/HerculesWS/Hercules/issues/2629, which shall be closed with a commit fixing this.

Comment (Kenpachi2k13) [reply src/map/skill.c]: Since you highlighted me, I'll throw in my opinion about this...

I don't know where you see a mistreatment of the integer type here. The relation between 1/0 and true/false in C is just implicit. If `== true` was used, I'd agree with you.

`unit_movepos()` returns 0 on error and 1 on success, so checking for `== 1` is absolutely valid.
If custom code introduces a new return value, the one who adds it is responsible for validating all dependencies.

> There needs to be a compile error then.
How would you do this?

\**********
**But in the end, you are right. If `!= 0` is used, all possible side effects are excluded.** :+1:
\**********

Comment (guilherme-gm) [reply src/map/skill.c]: Ah, true, i totally agree.. I didn't thought about custom code when I did the change, sorry...
I may open a PR fixing it later today (~12 hours from now), but if you guys want to ship a follow up release earlier, feel free to do it before me. Thanks!

Comment (skyleo) [reply src/map/skill.c]: With mistreatment of integer type as bool I simply refer to implicit comparisons such as `if (some_int)` which makes you think that it's checking for `== true`.

Seems like I was really sleepy yesterday and saw a return 2 where there wasn't any. So there are at least no side-effects in our code-base, not that I know of any. 😅 
But yeah let's use `== 0` and `!= 0` for stuff like this when just fixing up implict comparison on non-bool types. Essentially chaging those comparisons and only looking at specific return values should be done in a separate commit at least, so that it's more noticeable.
