### PR TITLE
Fix/extend @fakename

### LINKED ISSUE #1966: fakename stops guild/party names from showing
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

When you have a fakename from using **@fakename**, your guild and party names and guild positions won't be shown.

In the function `clif_charnameack`, I was able to resolve this issue. I'm unsure if it has side effects, but seems to work okay so far!

Find:
```
			if (ssd->fakename[0] != '\0') {
				WBUFW(buf, 0) = cmd = 0x195;
				memcpy(WBUFP(buf,6), ssd->fakename, NAME_LENGTH);
				WBUFB(buf,30) = WBUFB(buf,54) = WBUFB(buf,78) = 0;
- 				break;
			}
+			else
- 			memcpy(WBUFP(buf,6), ssd->status.name, NAME_LENGTH);
+ 				memcpy(WBUFP(buf,6), ssd->status.name, NAME_LENGTH);
```

Also, this is not a bug, rather an undesired feature. I will try to figure out how PR works to see if I can do it myself.

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

### PR DESCRIPTION
**Pull request by Kenpachi2k13**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

 * Fix the issue, where not even the fake name shows up, when using `@fakename` in RE clients.
 * Add parameter `options` to `@fakename`, to be able to select which names will be displayed.

Closes #2168
Closes #1966

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

File: src/map/atcommand.c [hunk 1]
```diff
@@ -7845,39 +7845,53 @@ ACMD(monsterignore)
...
 ACMD(fakename)
 {
-	if (!*message)
-	{
-		if (sd->fakename[0])
-		{
+	char fake_name[NAME_LENGTH] = {'\0'};
+	int options = FAKENAME_OPTION_NONE;
+
+	if (*message == '\0' || sscanf(message, "%23s %3d", fake_name, &options) < 1) {
```
Comment (MishimaHaruna) [inline src/map/atcommand.c]: This will fail to match strings containing spaces, and incorrectly parse strings containing spaces and numbers.

For example, the following will have unexpected results:

- `@fakename Hello World` -> `fake_name`: "Hello", `options`: unmodified, `sscanf()` result: 1 ("World" discarded)
- `@fakename Hello World 1` -> `fake_name`: "Hello", `options`: unmodified, `sscanf()` result: 1 ("World 1" discarded)
- `@fakename Hello 1 World` -> `fake_name`: "Hello", `options`: 1, `sscanf()` result: 2 ("World" discarded)
- `@fakename Hello 123 1` ->  `fake_name`: "Hello", `options`: 123, `sscanf()` result: 2 ("1" discarded)

It might be easier to move the options flag as the first argument (with `sscanf(message, "%d %[^\n]", &options, fake_name)`), and handle the case where `*message != '\0'` but `sscanf() < 2`, by using `message` as is (so that the flag is optional). It would still create ambiguity for those that want to use a fakename such as "123 foo", but those could just use `@fakename 0 123 foo`.

Comment (Kenpachi2k13) [reply src/map/atcommand.c]: This won't work, since `sscanf()` would fail if only the fake name is passed because it tries to parse a number as first argument and thus returns 0.
Guess we have to work with quotation marks here...

Comment (MishimaHaruna) [reply src/map/atcommand.c]: I was thinking of something along the lines of:

```
	char buf[NAME_LENGTH] = "";
	char *fake_name = NULL;
	int options = FAKENAME_OPTION_NONE

	if (*message == '\0') {
		/* disable fakename */
	} else {
		if (sscanf(message, "%d %23[^\n]", &options, buf, &options) == 2) // new syntax
			fake_name = buf;
		else // old syntax
			fake_name = message;

		/* enable fakename */
	}
```

Comment (Kenpachi2k13) [reply src/map/atcommand.c]: Yeah, this looks good. :+1:

Comment (Kenpachi2k13) [reply src/map/atcommand.c]: Done.

File: doc/atcommands.txt [hunk 2]
```diff
@@ -968,10 +968,19 @@ If no position is given, the command defaults to headgear.
...
+If no parameter is passed, the character's real name will be re-applied.
+The <options> parameter is used, to modify which names will be displayed.
+The fake name will always be displayed, regardless of <options>.
+Valid <options> flags (combinable):
+  0 - Only the fake name is displayed. (Default value.)
+  1 - Display party name.
+  2 - Display guild name.
+  4 - Display guild position.
+  8 - Display clan position.
+ 16 - Display title.
```
Comment (Helianthella) [inline doc/atcommands.txt:983]: the enum in atcommand.h should be exposed to the script engine as constants rather than having magic numbers in the documentation

Comment (Kenpachi2k13) [reply doc/atcommands.txt:983]: Since you can't use those constants when executing @fakename, I don't see any benefit in this.
