### PR TITLE
Fixed merge behaviour of map zones. Fixes #572

### LINKED ISSUE #572: map_zone_db and GvG mapflag
Refer to this:
http://herc.ws/board/topic/302-introducing-hercules-map-zone-database/page-5#entry57634

It goes like this:

Boot the server, everything's working, PvP-specific skills and gear aren't working in castles since WoE isn't active.

WoE begins, GvG mapflag is applied and now all that stuff can be used.

WoE ends, GvG mapflag is turned off, now this is where it breaks, the next time WoE starts, mapflag won't properly apply and all WoE-specific stuff will be disabled since maps are treated as normal zones. Setting it manually with @mapflag doesn't work either. Only solution is to reload scripts or reboot and having to do this after every WoE isn't exactly desirable.

This is a rather serious issue that's been around for quite a long time.

### PR DESCRIPTION
**Pull request by k-py**
- Both "Normal" and "PK Mode" default zones will now be overwritten (instead of merged) by "GvG", "PvP" and "Battlegrounds" zones.
- Refactored some code to clarify intent.

### CODE REVIEW

File: src/map/map.c [hunk 1]
```diff
@@ -5275,12 +5275,13 @@ void read_map_zone_db(void) {
 		ShowStatus("Done reading '"CL_WHITE"%d"CL_RESET"' zones in '"CL_WHITE"%s"CL_RESET"'.\n", zone_count, config_filename);
 		
 		/* post-load processing */
+		map->zone_all.merge_type = MZMT_NEVERMERGE;
```
Comment (MishimaHaruna) [inline src/map/map.c]: I only see `MZMT_NEVERMERGE` and `MAMT_MERGEABLE` being used. If this relies zeroed/allocated zones having an implicit `MZMT_NORMAL` (0), I believe it'd be better to explicitly initialize those explicitly.

**Comment by k-py** [comment]
Indeed, that is a good idea. And after reviewing the code, it allowed me to realize that I had missed setting the merge_type for the "PK Mode" zone.

All done and branch rebased.

**Comment by MishimaHaruna** [comment]
Looks good, thank you very much! Merged
