### PR TITLE
Stop sending standalone players to API server

### LINKED ISSUE #3306: Issue with API server and autotraders on restart
Creating an issue for tracking this message from Dastgir in #3304; I will look into it

     Probably unrelated to this PR, but there's one more issue wherein API server is called for autotraders on restart, and we get bunch of Account not online errors

_Originally posted by @dastgirp in https://github.com/HerculesWS/Hercules/issues/3304#issuecomment-2199869256_

**Describe the bug**
If you have persistent autotraders and do have one or more autotraders during server startup, you get an error for each one:

```
[Error]: Cant set char online. Account not logged in: 2000003
```

**To Reproduce**
1. Setup a vending
2. `@autotrade`
3. Shutdown your server ( `./athena-start stop` )
4. Start the server again ( `./athena-start start` )
5. See error in console

**Expected behavior**
Autotraders should not cause errors during startup.

**Screenshots**
-

**System specs (please complete the following information):**
 - OS: 5.15.153.1-microsoft-standard-WSL2 (Unix)
 - Hercules Version v2024.07 (master from this date -- no release yet)
 - Mode: any
 - Packet version: any
 - Client type: any

**Plugins used or source modifications**
None

**Additional context**
From what I can tell so far, this comes from the fact that during autotrader loading (which happens in map-server), it will send to char which will then send to login, finally sending the list to API server which won't recognize it.

I believe we should either:
1. Not send to API
2. Create accounts in API if they are coming from autotrade

### PR DESCRIPTION
**Pull request by guilherme-gm**
### Pull Request Prelude
- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
When map-server starts up and loads autotraders ("standalone" characters), they eventually get sent to char and login server. Once this happen, login-server tries to connect those players in API server, failing, because these players never logged in.

Since those players won't ever be valid, since they are totally system-controlled, this change prevents login-server from sending those accounts to API server, solving the many errors that show up during startup.

I took the chance to convert the packets involved to struct format

**Issues addressed:** Fixes #3306 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

File: src/common/HPMDataCheck.h [hunk 1]
```diff
@@ -321,7 +326,7 @@ HPExport const struct s_HPMDataCheck HPMDataCheck[] = {
 		#define COMMON_HPMI_H
 	#endif // COMMON_HPMI_H
 	#ifdef COMMON_MAPCHARPACKETS_H
-		{ "PACKET_MAPCHAR_AGENCY_JOIN_PARTY_REQ", sizeof(struct PACKET_MAPCHAR_AGENCY_JOIN_PARTY_REQ), SERVER_TYPE_ALL },
+		{ "PACKET_MAPCHAR_AUTH_REQ", sizeof(struct PACKET_MAPCHAR_AUTH_REQ), SERVER_TYPE_ALL },
```
Comment (guilherme-gm) [inline src/common/HPMDataCheck.h:329]: uh... is that right? I did not remove `PACKET_MAPCHAR_AGENCY_JOIN_PARTY_REQ`, but `PACKET_MAPCHAR_AUTH_REQ` comes first, are those entries just ranges?

**Comment by skyleo** [comment]
There seem to be some HPM changes unrelated to your PR. (Stemming from something merged previously.  For the sake of easier reviewable and atomic Commits please split those changes unrelated to you out, if they are missing in master you may start with an "Update HPM Hooks" commit.

@MishimaHaruna is the HWSApi that does the HPM Hook updates broken atm?

**Comment by guilherme-gm** [comment]
yup, they are missing in master. updated it

**Comment by MishimaHaruna** [comment]
I fixed the failing HWSAPI bot builds, it was due to an expired GPG key. Because of that though, I caused a conflict here, can you please rebase?

File: src/common/HPMDataCheck.h [hunk 2]
```diff
@@ -326,7 +326,7 @@ HPExport const struct s_HPMDataCheck HPMDataCheck[] = {
...
```
Comment (guilherme-gm) [inline src/common/HPMDataCheck.h:329]: Changed to draft to avoid accidental merge;;

This seems wrong... I did not remove this structure and I am not sure why HPMHookGen is generating that... 

If I move the declaration to between `PACKET_MAPCHAR_AGENCY_JOIN_PARTY_REQ` and `PACKET_MAPCHAR_GUILD_EMBLEM` in mapcharpackets.h, then `PACKET_MAPCHAR_GUILD_EMBLEM` gets removed.

any ideas?

File: src/common/HPMDataCheck.h [hunk 3]
```diff
@@ -255,7 +255,7 @@ HPExport const struct s_HPMDataCheck HPMDataCheck[] = {
 		#define COMMON_BASE62_H
 	#endif // COMMON_BASE62_H
 	#ifdef COMMON_CHARLOGINPACKETS_H
-		{ "PACKET_CHARLOGIN_ONLINE_ACCOUNTS", sizeof(struct PACKET_CHARLOGIN_ONLINE_ACCOUNTS), SERVER_TYPE_ALL },
+		{ "PACKET_CHARLOGIN_SET_ACCOUNT_ONLINE", sizeof(struct PACKET_CHARLOGIN_SET_ACCOUNT_ONLINE), SERVER_TYPE_ALL },
```
Comment (guilherme-gm) [inline src/common/HPMDataCheck.h:258]: same here

File: src/common/HPMDataCheck.h (hunk 2 above)
Comment (MishimaHaruna) [reply src/common/HPMDataCheck.h:329]: Did you already try deleting `tools/HPMHookGen/doxyoutput/`? When I get weird output it's usually due to stale data in there and doxygen not regenerating it

Comment (guilherme-gm) [reply src/common/HPMDataCheck.h:329]: yes, I did (found about it today, ever wondered how this worked 😅 ) but deleting it and running `make` again still gives this output

Comment (MishimaHaruna) [reply src/common/HPMDataCheck.h:329]: It seems that the macro call `DEFINE_PACKET_ID()` without a trailing semicolon is throwing doxygen off and making it ignore the following struct definition.

The same is happening in `charloginpackets.h` to `PACKET_CHARLOGIN_ONLINE_ACCOUNTS` and in `charmappackets.h` to `PACKET_CHARMAP_GUILD_INFO_EMPTY` and `PACKET_CHARMAP_GUILD_INFO_EMBLEM`.

Adding semicolons at the end of macro calls seems a quick and dirty way to prevent doxygen from getting confused.
The actual root issue though is that these `*packets.h` headers that use the `DEFINE_PACKET_ID()` macro forgot to include `common/packetsmacro.h` (and some of them probably only include it indirectly and by coincidence). Adding that include explicitly solves the issue, allowing doxygen to replace the macros and parse the file correctly. I don't see any ill side-effects in adding it everywhere it's needed.

Comment (guilherme-gm) [reply src/common/HPMDataCheck.h:333]: Ahh nice!! It works perfectly. I added an extra commit updating other files that calls `DEFINE_PACKET_ID` and did not import `packetsmacro`, there were a few other entries missing

**Review by MishimaHaruna — APPROVED** [review]
